from __future__ import annotations
from typing import Protocol

class CodeIntelligenceProvider(Protocol):
    def validate_snapshot_binding(self, snapshot: dict) -> dict: ...
    def query(self, snapshot: dict, query: dict) -> dict: ...
    def diff(self, before_snapshot: dict, after_snapshot: dict, query: dict) -> dict: ...
